/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ResourcesSlugRouteImport } from './routes/resources_.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources_/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/our-story': typeof OurStoryRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/sustainability': typeof SustainabilityRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/our-story': typeof OurStoryRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/sustainability': typeof SustainabilityRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/our-story': typeof OurStoryRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRouteWithChildren
  '/resources': typeof ResourcesRoute
  '/sustainability': typeof SustainabilityRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/resources_/$slug': typeof ResourcesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/contact'
    | '/gallery'
    | '/our-story'
    | '/process'
    | '/products'
    | '/resources'
    | '/sustainability'
    | '/products/$slug'
    | '/resources/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/contact'
    | '/gallery'
    | '/our-story'
    | '/process'
    | '/products'
    | '/resources'
    | '/sustainability'
    | '/products/$slug'
    | '/resources/$slug'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/contact'
    | '/gallery'
    | '/our-story'
    | '/process'
    | '/products'
    | '/resources'
    | '/sustainability'
    | '/products/$slug'
    | '/resources_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  OurStoryRoute: typeof OurStoryRoute
  ProcessRoute: typeof ProcessRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResourcesRoute: typeof ResourcesRoute
  SustainabilityRoute: typeof SustainabilityRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/resources_/$slug': {
      id: '/resources_/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  OurStoryRoute: OurStoryRoute,
  ProcessRoute: ProcessRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResourcesRoute: ResourcesRoute,
  SustainabilityRoute: SustainabilityRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
